version: "3.5"

services:

  traefik:
    image: traefik:v1.5.1-alpine
    hostname: traefik
    command:
      - --api
      - --docker
      - --docker.watch
      - --docker.constraints=tag==web
      - --entryPoints=Name:http Address::80 Compress::true
      - --defaultEntryPoints=http
      - --metrics
      - --metrics.prometheus
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/null:/traefik.toml:rw
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    networks:
      - asyncy-frontend
      - asyncy-backend

  bootstrap:
    image: asyncy/platform-bootstrap
    hostname: bootstrap
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - application-volume:/asyncy
    ports:
      - "5000:5000"
    networks:
      - asyncy-backend
    environment:
      - ASSET_DIR=/asyncy
      - SENTRY_DSN=$SENTRY_DSN_BOOTSTRAP
      - ENVIRONMENT=alpha
      - ASYNCY_USER_ID=$ASYNCY_USER_ID

  git:
    image: asyncy/platform-git-server
    hostname: git
    labels:
      - "traefik.tags=web"
      - "traefik.backend=git"
      - "traefik.port=8888"
      - "traefik.frontend.rule=Host: git.${DNS:-asyncy.net}"
    ports:
      - "8888"
    networks:
      - asyncy-frontend
      - asyncy-backend
    environment:
      - DEPLOY_URL=http://bootstrap:5000/alpha/deploy
      - SENTRY_DSN=$SENTRY_DSN_GIT
      - ENVIRONMENT=alpha
      - ASYNCY_USER_ID=$ASYNCY_USER_ID
    volumes:
      - application-volume:/asyncy

  gateway:
    image: asyncy/platform-gateway
    hostname: gateway
    labels:
      - "traefik.tags=web"
      - "traefik.backend=gateway"
      - "traefik.port=8888"
      - "traefik.frontend.rule=Host: ${DNS:-asyncy.net}"
    ports:
      - "8888"
      - "8889"
    networks:
      - asyncy-frontend
      - asyncy-backend
    volumes:
      - application-volume:/asyncy
    environment:
      - SENTRY_DSN=$SENTRY_DSN_GATEWAY
      - ENVIRONMENT=alpha
      - ASYNCY_USER_ID=$ASYNCY_USER_ID
      - ENGINE_ADDR=engine:8084

  engine:
    image: asyncy/platform-engine
    hostname: engine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - application-volume:/asyncy
    ports:
      - "8084"
    environment:
      - logger_name=asyncy
      - logger_level=debug
      - SENTRY_DSN=$SENTRY_DSN_ENGINE
      - ENVIRONMENT=alpha
      - ASYNCY_USER_ID=$ASYNCY_USER_ID
    networks:
      - asyncy-backend

  prometheus:
    image: asyncy/platform-prometheus
    hostname: prometheus
    labels:
      - "traefik.tags=web"
      - "traefik.backend=prometheus"
      - "traefik.port=9090"
      - "traefik.frontend.rule=Host: prometheus.${DNS:-asyncy.net}"
    volumes:
      - prometheus-volume:/prometheus
    ports:
      - "9090"
    networks:
      - asyncy-backend

  grafana:
    image: asyncy/platform-grafana
    hostname: grafana
    labels:
      - "traefik.tags=web"
      - "traefik.backend=grafana"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host: grafana.${DNS:-asyncy.net}"
    ports:
      - "3000"
    networks:
      - asyncy-backend
    volumes:
      - grafana-volume:/var/lib/grafana

  logspout:
    image: gliderlabs/logspout:latest
    hostname: logspout
    networks:
      - asyncy-logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "LOGDNA_INGESTION_KEY=${LOGDNA_INGESTION_KEY}"
      - "SYSLOG_HOSTNAME='{{index .Container.Config.Labels \"com.docker.compose.project\"}}'"
      - "SYSLOG_STRUCTURED_DATA='logdna@48950 tag=\"${ASYNCY_USER_ID}\""
      - "SYSLOG_TAG='{{.Container.Config.Hostname}}'"
    command:
      syslog+tls://syslog-a.logdna.com:32443
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.20'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M

volumes:
  application-volume:
  prometheus-volume:
  grafana-volume:

networks:
  asyncy-frontend:
    driver: bridge
  asyncy-backend:
    driver: bridge
  asyncy-logging:
    driver: bridge
