version: "3.5"

services:

  ###
  # Frontend
  ###
  traefik:
    image: traefik:v1.5.1-alpine
    command:
      - --api
      - --docker
      - --docker.watch
      - --docker.constraints=tag==web
      - --entryPoints=Name:http Address::80 Compress::true
      - --defaultEntryPoints=http
      - --metrics
      - --metrics.prometheus
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/null:/traefik.toml:rw
    ports:
      - "80:80"
      - "8080:8080"  # Traefik Frontend
      - "443:443"
    networks:
      - asyncy-frontend
      - asyncy-backend

  # app:
  #   image: asyncy/platform-app
  #   labels:
  #     - "traefik.tags=web"
  #     - "traefik.backend=app"
  #     - "traefik.port=5000"
  #     - "traefik.frontend.rule=Host: app.${DNS:-asyncy.net}"
  #   ports:
  #     - "5000"
  #   networks:
  #     - asyncy-frontend

  # hub:
  #   image: asyncy/platform-hub
  #   labels:
  #     - "traefik.tags=web"
  #     - "traefik.backend=hub"
  #     - "traefik.port=5000"
  #     - "traefik.frontend.rule=Host: hub.${DNS:-asyncy.net}"
  #   ports:
  #     - "5000"
  #   networks:
  #     - asyncy-frontend

  bootstrap:
    image: asyncy/platform-bootstrap
    labels:
      - "traefik.tags=web"
      - "traefik.backend=bootstrap"
      - "traefik.port=5000"
      - "traefik.frontend.rule=Host: ${DNS:-asyncy.net}"
    environment:
      DNS: ${DNS:-asyncy.net}
    depends_on:
      - postgres
      - metabase
      - kibana
    networks:
      - asyncy-backend
    ports:
      - "5000"
    networks:
      - asyncy-frontend
      - asyncy-backend

  graphql:
    image: asyncy/platform-graphql
    labels:
      - "traefik.tags=web"
      - "traefik.backend=graphql"
      - "traefik.port=5000"
      - "traefik.frontend.rule=Host: api.${DNS:-asyncy.net}; PathPrefix: /graphql, /graphiql, /_postgraphile"
    ports:
      - "5000"
    depends_on:
      - postgres
    networks:
      - asyncy-frontend
      - asyncy-backend

  ###
  # Management
  ###
  metabase:
    image: metabase/metabase
    labels:
      - "traefik.tags=web"
      - "traefik.backend=metabase"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host: metabase.${DNS:-asyncy.net}"
    ports:
      - "3000"
    volumes:
      - metabase-volume:/metabase-data
    networks:
      - asyncy-backend

  ###
  # Backend
  ###
  graphql-private:
    image: asyncy/platform-graphql
    ports:
      - "5000"
    depends_on:
      - postgres
    networks:
      - asyncy-backend

  engine:
    image: asyncy/platform-engine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    depends_on:
      - rabbitmq
      - redis
      - fluentd
    environment:
      - logger_name=asyncy
      - logger_level=warning
      - logdna_key=ingestion_key
    networks:
      - asyncy-backend
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: asyncy.engine

  postgres:
    image: postgres:10.3-alpine
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432"
    networks:
      - asyncy-backend

  rabbitmq:
    image: rabbitmq:3.7.3-alpine
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    networks:
      - asyncy-backend

  redis:
    image: redis:alpine
    volumes:
      - redis-volume:/data
    networks:
      - asyncy-backend

  grafana:
    image: asyncy/platform-grafana
    labels:
      - "traefik.tags=web"
      - "traefik.backend=grafana"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host: grafana.${DNS:-asyncy.net}"
    ports:
      - "3000"
    depends_on:
      - bootstrap
    environment:
      - GF_DATABASE_URL=postgres://${GRAFANA_DB_USER:-grafana}:${GRAFANA_DB_PASS:-grafana}@${GRAFANA_DB_HOST:-postgres}:${GRAFANA_DB_PORT:-5432}/${GRAFANA_DB_NAME:-grafana}
    networks:
      - asyncy-backend

  fluentd:
    image: asyncy/platform-fluentd
    networks:
      - asyncy-backend
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    labels:
      - "traefik.tags=web"
      - "traefik.backend=elasticsearch"
      - "traefik.port=9200"
      - "traefik.frontend.rule=Host: elasticsearch.${DNS:-asyncy.net}"
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data
    ports:
      - "9200"
    networks:
      - asyncy-backend

  kibana:
    image: asyncy/platform-kibana
    labels:
      - "traefik.tags=web"
      - "traefik.backend=kibana"
      - "traefik.port=5601"
      - "traefik.frontend.rule=Host: kibana.${DNS:-asyncy.net}"
    ports:
      - "5601"
    networks:
      - asyncy-backend

  statsd:
    image: prom/statsd-exporter:v0.6.0
    command: -statsd.listen-udp=:8125 -statsd.listen-tcp=:8125
    ports:
      - "8125"
      - "9102"
    networks:
      - asyncy-backend

  prometheus:
    image: asyncy/platform-prometheus 
    labels:
      - "traefik.tags=web"
      - "traefik.backend=prometheus"
      - "traefik.port=9090"
      - "traefik.frontend.rule=Host: prometheus.${DNS:-asyncy.net}"
    volumes:
      - prometheus-volume:/prometheus
    ports:
      - "9090"
    networks:
      - asyncy-backend

volumes:
  postgres-volume:
  rabbitmq-volume:
  redis-volume:
  metabase-volume:
  elasticsearch-volume:
  prometheus-volume:

networks:
  asyncy-frontend:
    driver: bridge
  asyncy-backend:
    driver: bridge
